apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: cpa
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: cpa
    app.kubernetes.io/name: cpa
    app.openshift.io/runtime: java
  name: cpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpa
  template:
    metadata:
      labels:
        app: cpa
    spec:
      containers:
      - name: cpa
        imagePullPolicy: Always
        image: image-registry.openshift-image-registry.svc:5000/mok/cpa:f0ac05de30bca1423a75bf1736d0fb4e4a0f8d90
        ports:
        - containerPort: 8381
          protocol: TCP
